### ISSUE TITLE
Version 0.2.6 not longer available on pypi

### ISSUE THREAD

**Issue by jricardo27** [organizerconnect/django-bouncy#1]
Hi,
Is there a reason for deleting the old 0.2.6 from pypi repo?

It is pretty much standard that packages keep old versions available on pypi so current projects can still be installed without needing to upgrade to the latest version of every package.

**Comment by siovene** [comment]
I'm also affected by this. Can 0.2.6 please be uploaded to PyPy again?

**Comment by nickcatal** [comment]
Ugh, that was a mistake on my end when creating this fork. All the old versions should be up on pypi now. Apologies here.
